name: Tests Main

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  dev:
    uses: ./.github/workflows/tests.yml
    with:
      io: "not io"
      os: "ubuntu-latest"